name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # 每天自动运行
  workflow_dispatch: # 允许手动运行

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4

      - name: Sync upstream
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh repo sync ${{ github.repository }} -b main
